<div class="content-header">
	<table cellspacing="0">
		<tr>
			<td><h3 class="head-dashboard"><?php echo $this->__('Cron') ?></h3></td>
		</tr>
	</table>
</div>

<div class="entry-edit">
	<div class="entry-edit-head">
		<h4><?php echo $this->__('List of all cron Jobs') ?></h4>
	</div>
	<fieldset class="bold">
		<?php foreach($this->getCron() as $cron):?>
			<p><?php echo $cron['name'] ?></p>
		<?php endforeach; ?>
	</fieldset>
</div>
