<?php if (Mage::helper('tangkoko_admintools')->isDateActive()): ?>
		<div id="date_header" style="padding-top: 0px;">
			<?php 
				echo $this->showServerTime(); 
				echo $this->showLocaleTime();
			?>
		</div>
		<script type="text/javascript">
			var date = 	$('date_header');
			var header_top = $$('div.header-top')[0];
			
			date.addClassName('header-right');
			header_top.insert({
				after: date
			});
		</script>
<?php endif; ?>
