
<div class="content-header">
    <table cellspacing="0">
        <tr>
            <td><h3 class="head-dashboard"><?php echo $this->__('PhpInfo') ?></h3></td>
        </tr>
    </table>
</div>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4><?php echo $this->__('Configuration') ?></h4>
    </div>
    <fieldset class="bold">
        <table class="form-list" cellspacing="0">
            <tbody>
            <tr>
                <td class="label">
                    <label for="srcLog">
                        <?php echo $this->__('Choose your level') ?>
                    </label>
                </td>
                <td class="value">
                    <select name="phpinfoLevel" id="phpinfoLevel" onChange="refreshPhpinfoLevel()" style="width:250px;">
                        <option value="<?php echo Mage::helper("adminhtml")->getUrl("tangkoko_admintools/adminhtml_phpinfo/displayPhpInfo/", array("levelInfo" => INFO_ALL)); ?>">INFO_ALL</option>
                        <option value="<?php echo Mage::helper("adminhtml")->getUrl("tangkoko_admintools/adminhtml_phpinfo/displayPhpInfo/", array("levelInfo" => INFO_GENERAL)); ?>">INFO_GENERAL</option>
                        <option value="<?php echo Mage::helper("adminhtml")->getUrl("tangkoko_admintools/adminhtml_phpinfo/displayPhpInfo/", array("levelInfo" => INFO_CREDITS)); ?>">INFO_CREDITS</option>
                        <option value="<?php echo Mage::helper("adminhtml")->getUrl("tangkoko_admintools/adminhtml_phpinfo/displayPhpInfo/", array("levelInfo" => INFO_CONFIGURATION)); ?>">INFO_CONFIGURATION</option>
                        <option value="<?php echo Mage::helper("adminhtml")->getUrl("tangkoko_admintools/adminhtml_phpinfo/displayPhpInfo/", array("levelInfo" => INFO_MODULES)); ?>">INFO_MODULES</option>
                        <option value="<?php echo Mage::helper("adminhtml")->getUrl("tangkoko_admintools/adminhtml_phpinfo/displayPhpInfo/", array("levelInfo" => INFO_ENVIRONMENT)); ?>">INFO_ENVIRONMENT</option>
                        <option value="<?php echo Mage::helper("adminhtml")->getUrl("tangkoko_admintools/adminhtml_phpinfo/displayPhpInfo/", array("levelInfo" => INFO_VARIABLES)); ?>">INFO_VARIABLES</option>
                        <option value="<?php echo Mage::helper("adminhtml")->getUrl("tangkoko_admintools/adminhtml_phpinfo/displayPhpInfo/", array("levelInfo" => INFO_LICENSE)); ?>">INFO_LICENSE</option>
                    </select>
                </td>
            </tr>
            </tbody>
        </table>
    </fieldset>
</div>

<iframe id="iframePhpinfo" style="border: none" width="100%" height="25000" src="<?php echo Mage::helper("adminhtml")->getUrl("tangkoko_admintools/adminhtml_phpinfo/displayPhpInfo/", array("levelInfo" => INFO_ALL)); ?>"></iframe>