<?php
/**
 * MagPleasure Ltd.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE-CE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://www.magpleasure.com/LICENSE-CE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This package designed for Magento COMMUNITY edition
 * MagPleasure does not guarantee correct work of this extension
 * on any other Magento edition except Magento COMMUNITY edition.
 * Magpleasure does not provide extension support in case of
 * incorrect edition usage.
 * =================================================================
 *
 * @category   MagPleasure
 * @package    Magpleasure_Massshipping
 * @version    1.0.3
 * @copyright  Copyright (c) 2012-2013 MagPleasure Ltd. (http://www.magpleasure.com)
 * @license    http://www.magpleasure.com/LICENSE-CE.txt
 */
?>
<div class="ms-upload">
    <div class="ms-block ms-common-buttons">
        <?php echo $this->getChangeMehtodButtonHtml(); ?>
    </div>
    <div class="ms-block ms-common-header">
        <h4><?php echo $this->__("Copy/Past from Excel"); ?></h4>
    </div>
    <div class="ms-block ms-common-content">

        <form id="past_excel" action="" method="post" enctype="multipart/form-data">
            <input type="hidden" name="form-key" value="<?php echo $this->getFormKey(); ?>" />
            <div class="paste-container" onclick="">
                <textarea name="paste_field" id="paste_field" rows="" cols=""></textarea>

                <div class="label-container">
                    <label for="paste_field"><strong><?php echo $this->__("Paste Your List"); ?></strong></label>
                    <div class="fixed"></div>
                </div>
                <div class="browse-button"><?php echo $this->getBrowseButtonHtml(); ?></div>
            </div>
        </form>
        <div class="fixed"></div>
        <script type="text/javascript">
            <?php echo $this->getJsName(); ?>.registerForm($('past_excel'));
        </script>


    </div>
    <div class="ms-block ms-common-footer">
        <?php echo $this->getImportButtonHtml(); ?>
    </div>
</div>